/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const requests_Logic = require('./code/requests-logic');
const requests_Logic2 = require('./code/requests-logic2');

class cap_request extends LCAPApplicationService {
    async init() {

        this.on('createDraft', 'Requests', async (request, next) => {
            await requests_Logic(request);
            return next();
        });

        this.on('CREATE', 'Requests', async (request, next) => {
            await requests_Logic2(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    cap_request
};